version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
  adminer-docker:
    image: michalhosna/adminer
    ports:
      - "8080:8080"
    environment:
        ADMINER_AUTOLOGIN: 1

###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###
