version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
  adminer-docker:
    image: michalhosna/adminer
    ports:
      - "8080:8080"
    environment:
        ADMINER_DB: ${POSTGRES_DB:-app}
        ADMINER_USERNAME: ${POSTGRES_USER:-app}
        ADMINER_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
        ADMINER_DRIVER: pgsql
        ADMINER_SERVER: database
        ADMINER_AUTOLOGIN: 1

###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###
